### ISSUE TITLE
Error: No match found for keyword 'getNumberOfPlayers()'

### ISSUE THREAD

**Issue by Respawnz** [Zezombye/overpy#100]
~~It is available in auto-complete and found in below link
https://github.com/Zezombye/overpy/blob/master/FUNCTIONS.md~~

Finally , I found it's just Error Message not correct.
This happen to `getTotalTimeElapsed()`(auto-complete) too.
So after I tried decompile workshop text to opy ,I found `getTotalTimeElapsed`(without bracket) is working good, And `getNumberOfPlayers(Team.ALL)` will pass the compile too.

**Comment by Zezombye** [comment]
getNumberOfPlayers() shouldn't work, as it takes a team argument.

I fixed the getTotalTimeElapsed(), thanks for reporting :)

**Comment by Respawnz** [comment]
Thanks for response. OverPy is really awesome !
