### ISSUE TITLE
"Found if but not else" in filtered array using "Is true for any".

### ISSUE THREAD

**Issue by nathan130200** [Zezombye/overpy#136]
I'm creating a respawn mechanisms system, that will select first position that check if any player is in line of sight:

```python
subroutine PayloadPositionSelector

@Rule "[ Has Spawned ]: Random Payload Position"
@Event eachPlayer
@Team 1
if eventPlayer.isAlive() and respawnType == RESPAWN_PAYLOAD:
	eventPlayer.respawnPositionFound = false
	PayloadPositionSelector()
	eventPlayer.teleport(eventPlayer.respawnPosition)

@Rule "[ Respawn ]: Payload Position Selector"
def PayloadPositionSelector():
	do:
		eventPlayer.respawnPosition = random.choice([x for x in respawnPositions if distance(getPayloadPosition(), x) >= RESPAWN_PAYLOAD_MIN_DISTANCE and distance(getPayloadPosition(), x) <= RESPAWN_PAYLOAD_MAX_DISTANCE])		
		if not any([x for x in getPlayers(Team.2) if raycast(eventPlayer.respawnPosition, eventPlayer.getPosition()).hasLoS()]):
			eventPlayer.respawnPositionFound = true
			
	while not eventPlayer.respawnPositionFound
```

Display error in compiler at  `if not any([x for x in getPlayers(Team.2) if raycast(eventPlayer.respawnPosition, eventPlayer.getPosition()).hasLoS()]):` 

> Error: Found 'if' but no 'else'.

But in wiki say: `any([elem for elem in array if condition])` to use `Is True For Any`,

**Comment by Zezombye** [comment]
The wiki was wrong, thanks for reporting.

It should instead be `any([condition for elem in array])`, such as `any([player.hero == Hero.ANA for player in getAllPlayers])`.
