### ISSUE TITLE
Unexcepted function @Rule outside a rule.

### ISSUE THREAD

**Issue by nathan130200** [Zezombye/overpy#143]
Contents of Castillo.opy:
```python
#!mainFile "Pathfind.opy"

@Rule "Map: Castillo"
@Event global
if getCurrentMap() == Map.CASTILLO:
    nodeArray = []
    nodeArray.append(vect(-122.537, 34.569, 51.639))
    nodeArray.append(vect(-122.136, 34.569, 47.156))
    nodeArray.append(vect(-121.292, 33.554, 42.88))
    nodeArray.append(vect(-117.92, 32.555, 40.061))
    nodeArray.append(vect(-116.805, 32.555, 35.696))
    nodeArray.append(vect(-116.793, 32.569, 30.05))
    nodeArray.append(vect(-113.839, 32.569, 27.312))
    nodeArray.append(vect(-109.386, 32.556, 29.121))
    nodeArray.append(vect(-106.213, 32.558, 31.88))
    nodeArray.append(vect(-101.402, 32.558, 32.755))
    # Too many lines...
```

![image](https://user-images.githubusercontent.com/14365254/80923920-c03dba80-8d5c-11ea-8086-6e751108e322.png)
![image](https://user-images.githubusercontent.com/14365254/80923881-a8fecd00-8d5c-11ea-8192-768d9c7d48be.png)

I tried both `@Rule` and `@Name`:
![image](https://user-images.githubusercontent.com/14365254/80923997-11e64500-8d5d-11ea-80c3-1e418da2af8c.png)
![image](https://user-images.githubusercontent.com/14365254/80923995-07c44680-8d5d-11ea-988d-7a3e8b20b9e3.png)

OverPy syntax changed?

> Note: My VSCode updated overpy extesion now, i didn't see in wiki changes about syntax.

**Comment by nathan130200** [comment]
This version is totally broken, i cannot compile and decompile anything.

![image](https://user-images.githubusercontent.com/14365254/80924286-75bd3d80-8d5e-11ea-92c2-09353063e0f4.png)
![image](https://user-images.githubusercontent.com/14365254/80924287-78b82e00-8d5e-11ea-885d-632fad1187c7.png)

Also decompiler UI:
![image](https://user-images.githubusercontent.com/14365254/80924298-8d94c180-8d5e-11ea-94db-3ab89c02ac2a.png)

**Comment by Zezombye** [comment]
The 5.0 version comes with breaking changes: https://github.com/Zezombye/overpy/releases/tag/v5.0.0

I am currently working on restoring the decompiler functionality.

**Comment by nathan130200** [comment]
Ok, thank you!

**Comment by Zezombye** [comment]
They already are added, putting a line comment before or after (but on the same logical line) an action will put that comment in the output.

**Comment by nathan130200** [comment]
Nice!

**Comment by nathan130200** [comment]
I have also another question, why instead using `tabs` to indent blocks (that is horrible) why not use curly braces to recognize as code blocks?

**Comment by Zezombye** [comment]
Weird, I specifically chose python syntax because I found it cleaner than the braces syntax. I guess I could add braces but it would be annoying to differenciate them from dictionaries. What do you not like about tabs?

And ye fuck snake_case, all my homies use camelCase.

**Comment by nathan130200** [comment]
In the real don't make difference for me tabs xD, is that I thought funny, the syntax of snake_case and camelCase together. Just some brain confusion.
