### ISSUE TITLE
Does Overpy plan to support object-oriented programming?

### ISSUE THREAD

**Issue by SweetInk** [Zezombye/overpy#200]

**Comment by Zezombye** [comment]
Nope as:

- I try to keep the language relatively simple, such that one may do the compilation "in their head". Classes would be quite complex to implement.
- As the workshop itself does not have classes, I would have to do a runtime implementation (with several variables and rules), something I try not to do.

What would object-oriented programming be useful for?

**Comment by SweetInk** [comment]
Recently, I intend to design a parkour editor, in which "Death Zone", I use several arrays to store related attributes.

```python
deathZoneLocations = []
deathZoneRadius = []
deathZoneDamages = []
```
If there are more attributes, then I need more arrays.

Or, to put it another way, use a similar structure to store some simple attribute values.

**Comment by Zezombye** [comment]
If the arrays are filled at runtime (as it is a parkour editor), I don't feel this is that much of a problem: you'd just write deathZoneLocations[x] instead of deathZone.locations[x].

If the arrays are filled at the start, then you can use a JS macro that splits the object into several arrays: https://github.com/Zezombye/overpy/blob/master/examples/old/Zombie%20Escape/maps/BlizzardWorld.opy

**Comment by SweetInk** [comment]
> If the arrays are filled at runtime (as it is a parkour editor), I don't feel this is that much of a problem: you'd just write deathZoneLocations[x] instead of deathZone.locations[x].
> 
> If the arrays are filled at the start, then you can use a JS macro that splits the object into several arrays: https://github.com/Zezombye/overpy/blob/master/examples/old/Zombie%20Escape/maps/BlizzardWorld.opy

Thank you. I had a compilation error when I used JS macro.
`stack trace`
```
Error: ReferenceError: eventPlayer is not defined | line 1, col 13, at test.js | line 5, col 5, at <main>
```
`opy code`
```
#!define testMacro(obj) __script__("test.js")

rule "test macro":
    @Event eachPlayer
    testMacro({
        loc:eventPlayer.getPosition()
    })
```
`test.js`
```javascript
var result = "";
result=`deathZones.append(${obj.loc})`;
result;
```

**Comment by Zezombye** [comment]
Yup, as it believes `eventPlayer` is a javascript variable.

It should be:

```python
rule "test macro":
    @Event eachPlayer
    testMacro({
        loc: "eventPlayer.getPosition()"
    })
```
