### ISSUE TITLE
What's this Mapped Array for?

### ISSUE THREAD

**Issue by 2020snc** [Zezombye/overpy#207]
overpy
```
#!disableOptimizations
rule "1":
    A = [p for p in getAllPlayers() if p.A == 1]

```
compile result
```
rule ("1") {
        event {
            Ongoing - Global;
        }
        actions {
            Set Global Variable(A, Mapped Array(Filtered Array(All Players(All Teams), Compare((Current Array Element).A, ==, 1)), Current Array Element));
        }
    }
```

**Comment by Zezombye** [comment]
The grammar of overpy (which, for now, is just in my head lol) specifies that `[a for b in c if d]` is compiled to `mapped array(filtered array(c, d), a)`.

As you disabled optimizations, it did not remove the mapped array (which indeed does nothing as it just maps every element to itself).
