### ISSUE TITLE
An issue with array append

### ISSUE THREAD

**Issue by SweetInk** [Zezombye/overpy#208]
```opy code
rule "test":
    X.append([1,2,3])
    X.append([4,5,6])
```
`expect result`: `[[1,2,3],[4,5,6]]`
`actual result`:`[1,2,3,4,5,6]`

**Comment by Zezombye** [comment]
This is actually a workshop behavior, nothing I can do here.

Does `X.append([[1,2,3]])` work for your purposes?

**Comment by SweetInk** [comment]
I use array to simulate object instance.
Similar to the following code

```javascript
var objA = {
  i:1,
  j:2,
  a:[]
};
objA.append({
 p1:"p1",
 p2:"p2"
});
```

`opy code`

```python
rule "test":
    A[0]=1
    A[1]=2
    A[2].appen(["p1","p2"])
```

**Comment by Zezombye** [comment]
Yes, `append to array` is the equivalent of `extend`.

Does `append([["p1", "p2"]])` work?

**Comment by SweetInk** [comment]
Not work,but I define the array directly, and it works correctly.
```python
A = [[1,2,3],[4,5]]
```

**Comment by SweetInk** [comment]
I know how to resolve it
just like this
```python
rule "test":
    A = []
    A.append([[1,2,3]])
    A.append([[3,4,5]])
```
Finnally, A's value `[[1,2,3],[4,5,6]]`
