### ISSUE TITLE
"Evaluated" is misspelled in the Reevaluation for Start Scaling Player and Start Scaling Barriers

### ISSUE THREAD

**Issue by Zomg15** [Zezombye/overpy#244]
`"If this value is true, then scale will be reevaluated and applied to the player or players every frame. If this value is false, then the scale is only avaluated once when the action begins."`

`"If this value is true, then scale will be reevaluated and applied to the player or players every frame. If this value is false, then the scale is only avaluated once when the action begins."`

Notice the "avaluated" where the word "evaluated" should be.

**Comment by Zezombye** [comment]
Fixed in 6.6.11, thanks for reporting!
