### ISSUE TITLE
Some variable names are considered reserved and cannot be decompiled

### ISSUE THREAD

**Issue by Provoxin** [Zezombye/overpy#252]
```
variables
{
	player:
		0: Invis
}

rule("Rule 1")
{
	event
	{
		Ongoing - Each Player;
		All;
		All;
	}

	actions
	{
		Event Player.Invis = True;
	}
}
```
Trying to decompile this results in
![image](https://user-images.githubusercontent.com/73077203/102822756-a2829b80-43a7-11eb-821f-6bdc65f1a67e.png)

**Comment by Zezombye** [comment]
Fixed in 6.8.11, thanks for reporting!
