### ISSUE TITLE
For multi-line text js macro's return contains extra spaces at the beginning of each line

### ISSUE THREAD

**Issue by Soulless-Me** [Zezombye/overpy#253]
test.opy
```python
#!define func(arg) __script__("test.js")


rule "Hello":
    A = func(
`
line 1
line 2
`
        )
```
test.js
```javascript
var arg;
console.log(arg, typeof (arg), arg.length);
'"' + arg + '"';
```

result:
```c#
variables {
    global:
        0: A
}
rule ("Hello") {
    event {
        Ongoing - Global;
    }
    actions {
        Set Global Variable(A, Custom String("\n    line 1\n    line 2\n    ", Null, Null, Null));
    }
}
```

console.log
![ScreenShot_2020-12-30_20-32-03](https://user-images.githubusercontent.com/74082054/103351446-38bc6d00-4ade-11eb-9287-357eec086c4f.png)

Did I do something wrong?

**Comment by Zezombye** [comment]
If the call to a macro is indented, the indentation is prepended to each line of the result. As overpy is indentation-based, this is necessary in order to make macros made of multiple actions.

If you don't want this behavior, you will need to manually declare the newlines:

```js
'"'+arg.replace(/\n/, "\\n")+'"'
```

**Comment by Soulless-Me** [comment]
This does work, Thank you zez!

**Comment by Soulless-Me** [comment]
Thank you again for making me understand why this is happening!
