### ISSUE TITLE
Prototype: Local variables inside rules.

### ISSUE THREAD

**Issue by nathan130200** [Zezombye/overpy#254]
Add possibility to declare and use rule and player variables as local variables in rules, for example declare temporary data then delete everything (setting to null, `not false, because, false has 1 byte size`, in workshop works). OverPy can reserve an global ad player var called `_LocalVariableTable` both for player var and global var.

### Definition

For local variable that does not have an scope (using `globalvar` keyword) will store only Rule variables.
For local variable that is in player scope (using `playervar` keyword) will store only Rule variables relative to eventPlayer, victim or attacker.

### Remarks
- Once "local" variable is define at player scope, same variable name will be displayed/used for both, attacker, victim or eventPlayer.
- We have partial multi dimentional arrays in workshop, we can store only arrays in immmutable copy for sub array, since we cannot modify value inside an sub array, inside an array (we cannot access `Global.myArr[0][1]` workshop rejects syntax) but works, in inspector will display `Array of ?? elements`, only can set sub dimentional array, with new `Array( ... )` syntax.
- Each array value changes in sub array, will need copy and modify array value, then update in `_LocalVariableTable` at correct scope.
- Also, since need copy, modify then update, idk if code generation in workshop will optimized for server load and stuff.
- Also server load maybe can be vary dependending on length of array, memory transfer, etc.
- Each rule, that have local variables will store in `_LocalVariableTable` in this way:
  - `_LocalVariableTable[index of unique rule identifier or identifier++] = Array( ... values ...)` during compilation.

### Example

```py
@Rule "Example 1: Global Scope"
@Event global
	# at start, opy, will translate globalvar in rule scope, and allocate an space in variable _LocalVariableTable in global scope
	globalvar count = 30
	
	# normal localvariable count (at global scope) access
	hudHeader(getAllPlayers(), "Count: {}".format(count), HudPosition.TOP, -1,
		Color.YELLOW, HudReeval.VISIBILITY_AND_STRING, SpecVisibility.DEFAULT)
	
	do:
		count--
		wait(1)
	while count > 0
	
	count = -1
	
	# at end, during workshop translation, `count` variable will be deleted
	
@Rule "Example 2: Player Scope"
@Event global
	# same in example1, except that, _LocalVariableTable will be stored in player.
	playervar respawnTime = 0
	playervar respawnTimeHudTextRef = -1
	
	# normal localvariable `respawnTime` in eventPlayer
	hudHeader(eventPlayer, "Respawn Time: {}".format(eventPlayer.respawnTime), HudPosition.RIGHT, -1,
		Color.YELLOW, HudReeval.VISIBILITY_AND_STRING, SpecVisibility.DEFAULT)
		
	respawnTimeHudTextRef = getLastCreatedText()
	
	do:
		respawnTime++
		wait(1)
	while respawnTime < 10
	
	destroyHudText(respawnTimeHudTextRef)
	
	# at end, during workshop translation, `respawnTime` variable will be deleted
```

In "example 1", at global scope (workshop syntax):
- `Global._LocalVariableTable[0] = Array(0)` when declare count variable and assign an value.
- `Global._LocalVariableTable[0] = Array(Global._LocalVariableTable[0][0] - 1)` when decrement `count--`
- `Global._LocalVariableTable[0][0] > 0` to compar if `count` is greater than zero.
- At rule ends `Global._LocalVariableTable[0] = Null` and release all variables.

In "example 2", at player scope (workshop syntax):
`Event Player._LocalVariableTable[0] = Array(0, -1);` when assign two variables with initial value.
`Event Player._LocalVariableTable[0] = Array(Event Player._LocalVariableTable[0][0], Last Created Text);` when assign hud text to last created text, will perform deep-copy of each elements.
`Event Player._LocalVariableTable[0] = Array(Event Player._LocalVariableTable[0][0] - 1, Event Player._LocalVariableTable[0][1]);` when decrement `respawnTime`, same array copying.
`Event Player._LocalVariableTable[0][0] < 10` When compare less than 10.
`Destroy Hud Text(Event Player._LocalVariableTable[0][1])` to remove hud text from player.
Then release all vars. `Event Player._LocalVariableTable[0] = Null;`

First array index in `Event Player._LocalVariableTable[0]` is `count of rules - 1` or can be an unique index, or randomized index (when use obfuscation, each compilation generate different indexes).

#### You can keep on hold, and wait if workshop devs will implement this soon.

**Comment by Zezombye** [comment]
First of all, thank you for submitting such a detailed suggestion!

```
@Rule "Example 1: Global Scope"
@Event global
	# at start, opy, will translate globalvar in rule scope, and allocate an space in variable _LocalVariableTable in global scope
	globalvar count = 30
```

Now this is a little syntaxic problem: using the `globalvar` keyword to generate a local variable... ^^

This can be solved by replacing `globalvar` with simply `var`.

```
# at end, during workshop translation, `count` variable will be deleted
```

I don't understand why the variables are deleted?

```
In "example 1", at global scope (workshop syntax):

    Global._LocalVariableTable[0] = Array(0) when declare count variable and assign an value.
    Global._LocalVariableTable[0] = Array(Global._LocalVariableTable[0][0] - 1) when decrement count--
    Global._LocalVariableTable[0][0] > 0 to compar if count is greater than zero.
```

So the first index is the rule index and the second index is the var index? Why not, though you could combine the two. Combining would reduce the problems with assigning to multidimensional arrays, but limit the number of total local variables to 1000, rather than a maximum of 1000 rules and 1000 local variables per rules.

As for the multidimensional array assignment problem, provoxin made a macro to do that in one action using array slice. I didn't put this macro natively due to the duplication (so it wouldn't work with `A[0][random.randint(1,2)]` but since here all values are constants, its use would be possible.

Now, it would be possible and I'd be up to implement it, but would it truly be an improvement? Personally I never felt the need for pseudo-local variables, putting a `globalvar` declaration just before a rule is enough.

**Comment by nathan130200** [comment]
Closing this issue, i tried replicate an real 'world' example, but yeah definitely will generate bunch of stuff to do minimal stuff.

- Array coping.
Using many `Array(...)` is best solution, but each value modified will trigger array copy for all its values and indexes. So if i wanna modify second element inside this array (considering this as multi dimentional array) i will must `temp = Array(temp[0], newValue, temp[2], temp[3], ..., temp[n])`
