### ISSUE TITLE
No match found for keyword "healingreceived"

### ISSUE THREAD

**Issue by cpbeaslin** [Zezombye/overpy#255]
as the title says, the decompiler will error with healing received

**Comment by Zezombye** [comment]
I can't reproduce it, can you give me the code with the error?

**Comment by cpbeaslin** [comment]
https://github.com/cpbeaslin/OverStat/blob/main/workshop.txt

**Comment by Zezombye** [comment]
Fixed in 6.7.2, thanks for reporting!
