### ISSUE TITLE
Unable to decompile workshop settings using enums

### ISSUE THREAD

**Issue by Saphirah** [Zezombye/overpy#262]
Hey, 

i am unable to decompile the following script. The error message is: No Match found for keyword '[3]'
So the problem probably is in this line (74-78)

workshop
{
    Difficulty: [3]
    Mode: [1]
}

Those are 2 Workshop Variables i created with a dropdown menu. Is there a way to resolve this? or is this a bug?

[Main.txt](https://github.com/Zezombye/overpy/files/5976854/Main.txt)

**Comment by Zezombye** [comment]
Fixed in 6.8.4, thanks for reporting!
