### ISSUE TITLE
Start Forcing Dummy Bot Name not decompiling

### ISSUE THREAD

**Issue by Saphirah** [Zezombye/overpy#263]
Hey,

i have the following code that renames a dummy bot to "Sniper". Whenever i try to decompile it, i get the error:
`Error: Unhandled expected type '"FloatLiteral"' or received type 'undefined'`

rule("Widow Setup")

{
	event
	{
		Ongoing - Each Player;
		Team 2;
		Widowmaker;
	}

	conditions
	{
		Is Dummy Bot(Event Player) == True;
	}

	actions
	{
		Start Forcing Dummy Bot Name(Event Player, Custom String("Sniper"));
	}
}

**Comment by Zezombye** [comment]
Fixed in 6.8.5, thanks for reporting!
