### ISSUE TITLE
Decompiling with all extensions activated will add #!extension undefined

### ISSUE THREAD

**Issue by Saphirah** [Zezombye/overpy#264]
Hey,

whenever i decompile a workshop script with all extensions activated the decompiler will add the line 
`#!extension undefined` at the end of all activated extensions.

This prevents the resulting opy script from compiling.
[Code.txt](https://github.com/Zezombye/overpy/files/5977735/Code.txt)
[Code_opy.txt](https://github.com/Zezombye/overpy/files/5977736/Code_opy.txt)

**Comment by Zezombye** [comment]
Fixed in 6.8.6, thanks for reporting!
