### ISSUE TITLE
Copy to clipboard doesn't work on Linux (Ubuntu)

### ISSUE THREAD

**Issue by LionariusPy** [Zezombye/overpy#277]

**Comment by Zezombye** [comment]
Currently I'm using https://www.npmjs.com/package/copy-paste, I guess I'll have to try out https://www.npmjs.com/package/clipboardy.

Is there a reason you are using linux instead of windows ?

**Comment by LionariusPy** [comment]
I have both windows and linux installed on my pc, so this bug isn't really critical for me

**Comment by Zensonaton** [comment]
can confirm that copy to clipboard isn't working on manjaro linux, "KDE" desktop environment.

**Comment by Zezombye** [comment]
I want to see if it is fixed for lionariuspy as well :p
