### ISSUE TITLE
Error when importing with obscurity 

### ISSUE THREAD

**Issue by Mazawrath** [Zezombye/overpy#278]
I am trying to import the code in [this branch,](https://github.com/Mazawrath/Overwatch-Genji-Dodgeball/tree/v7.4.0) only with the `#!obfuscate` option added on the second line of `Genji-Dodgeball.opy`. This code compiles fine and can be sucessfuly pasted into Overwatch. The issue happens when I add the flag.
The attached file is the output I am getting:
[settings.txt](https://github.com/Zezombye/overpy/files/7214736/settings.txt)
And when I try to import the settings, Overwatch outputs this error:
```Error: Expected a map name after 'Map(' on line 474```

Any help would be appreciated.

**Comment by Mazawrath** [comment]
Doing some more research this even happens in my master branch. So not too sure what actually caused this.

**Comment by Zezombye** [comment]
Right, they still haven't added Malevento to live so the `Map(Malevento)` gives an error.

I'll release an update to remove it, in the meanwhile you'll have to ctrl+f "malevento" in the output and replace it by whatever map you want.
