### ISSUE TITLE
Missing translations for "modeName" in customGameSettings.main

### ISSUE THREAD

**Issue by charles2hang** [Zezombye/overpy#279]
![image](https://user-images.githubusercontent.com/21257369/136109281-504719c9-26c5-449a-8dbc-6210d7d81d95.png)
Perhaps because of missing "guid" in original data? Not sure about that.
Here's the translation in zh-CN just in case:
```json
"modeName": {
    "values": "__string__",
    "maxChars": 32,
    "en-US": "Mode Name",
    "zh-CN": "模式名称",
}
```

**Comment by Zezombye** [comment]
Fixed in 6.10.2, thanks for reporting!
