### ISSUE TITLE
(french) decompiling fails when "create dummy bot" is in the code

### ISSUE THREAD

**Issue by yubber** [Zezombye/overpy#287]
![image](https://user-images.githubusercontent.com/39871798/142757234-17578722-53fc-432c-9e7f-2cb646e0ddaa.png)

in workshop the text is
`Créer une I.A.`

**Comment by Zezombye** [comment]
Duplicate of #249, but I'll take a look at handling this issue via a hack if users actually use overpy with french workshop.
