### ISSUE TITLE
(enhancement?) add option to disable copying compiled code to clipboard if compilation is triggered by save

### ISSUE THREAD

**Issue by yubber** [Zezombye/overpy#288]
without linting, the error messages from the compiler every time you save are the only way to see errors as you type (for autosave).

but this also means that cutting code to the clipboard or typing something before pasting will end up making you paste all the compiled code into the program (which frightened me a few times)

**Comment by Zezombye** [comment]
There is already an option for that in the extension settings:

![](https://i.imgur.com/EeeMZGS.png)
