### ISSUE TITLE
french custom game settings not using required special character

### ISSUE THREAD

**Issue by yubber** [Zezombye/overpy#290]
the game expects a " " (U+00a0) instead of a normal space in the `heroes` part of the custom game settings. this causes exported code to have an error in the custom game settings.

```
héros
	{
		Équipe 1 <-- here, in between Équipe and the number
		{
			Génération de capacité ultime - Combat: 0%
		}
		Équipe 2 <-- here in the same spot
		{
			Génération de capacité ultime - Combat: 500%
		}
	}
```

when exporting, opy still uses the correct character in the lobby section of the custom game settings (namely here: `Joueurs max. dans Équipe 1.: 1`)

sample opy code that exports to errant code (with correct character in lobby section):
```
settings {
    "lobby": {
        "team1Slots": 1,
        "team2Slots": 0,
    },
    "gamemodes": {
        "skirmish": {
            "enabledMaps": [
                "volskaya"
            ]
        }
    },
    "heroes": {
        "team1": {
            "general": {
                "combatUltGen%": 0
            }
        },
        "team2": {
            "general": {
                "combatUltGen%": 500
            }
        }
    }
}
```

**Comment by Zezombye** [comment]
Fixed in 6.11.4, thanks for reporting! There were 2 guids, let's hope I got the right one and it doesn't cause problems in the other translations lul.
