### ISSUE TITLE
Macros with brackets and comments throw errors

### ISSUE THREAD

**Issue by pharingWell** [Zezombye/overpy#292]
##### Issue type
- Bug Report
##### OverPy version
zezombye.overpy v6.11.4 (Last Updated: 12/24/2021, 06:59:16)

##### Summary
Error thrown incorrectly

##### Steps to reproduce
![image](https://user-images.githubusercontent.com/30706897/148706239-75a1432f-7817-4f5f-a2ff-2eff41399526.png)

Put a comment in-line with a macro that ends in a bracket
##### Expected results
Ignores the comment and does not pass it

##### Actual results
Throws this error
![image](https://user-images.githubusercontent.com/30706897/148706282-5c68833f-21ba-434d-b11d-e11bd773ce14.png)

**Comment by Zezombye** [comment]
Macros are literally copy-pasted into the code, so the comment "eats" the rest of the line where it is called :p

To fix it, use an inline comment `/**/` or put the comment on the line above.
