### ISSUE TITLE
'Modify Global Variable At Index' Get error

### ISSUE THREAD

**Issue by millionart** [Zezombye/overpy#3]
try this code will get an error occurred:

`
rule("test")
{
    event
    {
        Ongoing - Global;
    }
    actions
    {
        Modify Global Variable At Index(A, 1, Add, 1);
    }
}
`

**Comment by Zezombye** [comment]
Fixed in 1.1, thanks for reporting! Make sure to clear your cache if you are testing on the demo page (ctrl+F5).
