### ISSUE TITLE
Workshop Expanse Night and Workshop Island Night preventing compilation

### ISSUE THREAD

**Issue by joksulainen** [Zezombye/overpy#304]
When you try to compile a script with either of those two maps listed as disabled or enabled it will just say that it can't be pasted and has to be done through UI. This wouldn't be an annoyance if it just skipped them instead of halting compilation.

**Comment by Zezombye** [comment]
Right, I guess I could demote to warning so that when the bug is fixed you won't have to add them back.

**Comment by Zezombye** [comment]
Done in 6.12.11
