### ISSUE TITLE
Cant set cooldown for genjis ability 1

### ISSUE THREAD

**Issue by Totorooww** [Zezombye/overpy#306]
Every other ability for all heroes works, including genjis ability 2, I've isolated everything I possibly can and have confirmed that the condition does work.

Here's the code for the action that isn't working:
`eventPlayer.setAbilityCooldown(Button.ABILITY_1, eventPlayer.getAbilityCooldown(Button.ABILITY_1) * 0.5)`

This is an example of a line that did work for his E:
`eventPlayer.setAbilityCooldown(Button.ABILITY_2, eventPlayer.getAbilityCooldown(Button.ABILITY_2) * 0.5)`

**Comment by Zezombye** [comment]
It's a workshop bug, they did something sussy to his dash.

**Comment by Totorooww** [comment]
Ok thanks, hope they fix it quickly
