### ISSUE TITLE
Incorrect behavior with switch and loop if condition is true

### ISSUE THREAD

**Issue by pharingWell** [Zezombye/overpy#311]
The skip statement called near valueInArray in the switch function causes currentRuleHasVariableGoto to be set to true, as valueInArray is not distanceTo.

A temporary fix was done by adding "&& content.args[0].name != "__valueInArray__"" to the __distanceTo_ check, but I have no idea what problems that could cause elsewhere

**Comment by Zezombye** [comment]
Fixed in 6.13
