### ISSUE TITLE
Switch to a more standard codebase and build pipeline

### ISSUE THREAD

**Issue by netux** [Zezombye/overpy#351]
The current way files are split is very developer unfriendly, as we get basically no IntelliSense.
Debugging is okayish because of demo.html and DevTools, but it could be better.

Consider linking all files through module imports/exports, and building with standard tools like Parcel/Rollup/Snowpack/esbuild.

**Comment by CactusPuppy** [comment]
If I ever get enough time to dedicate to this, I would love to tackle it. It's quite an overhaul at the moment though.

**Comment by CactusPuppy** [comment]
This can't happen soon enough.

**Comment by CactusPuppy** [comment]
Closed in #366
