### ISSUE TITLE
Add the rest of the "Enable/Disable" actions

### ISSUE THREAD

**Issue by Ciach0** [Zezombye/overpy#365]
Currently, there are options to enable/disable:
- The Announcer, 
- Game Mode Completion, 
- Workshop Inspector, 
- Music,
- Scoring

But OverPy lacks some actions, that being:
Enable/Disable:
- Respawning, 
- Death Spectate Players, 
- Death Spectate Target Hud, 
- Game Mode Hud, 
- In-World UI, 
- Hero Hud, 
- Kill Feed, 
- Collision with Environment, 
- Collision with Players,
- Nameplates, 
- Scoreboard, 
- Text Chat,
- Voice Chat

It's very tedious when I have to resort to writing the lacking directives myself, and adding them to OverPy would help overcome it

**Comment by CactusPuppy** [comment]
I believe the actions you have highlighted as missing are actually just only available in a player context, like so:

```py
rule "Disable/enable a lot of things":
  getAllPlayers().disableRespawn()
  getAllPlayers().disableDeathSpectateAllPlayers()
  getAllPlayers().disableDeathSpectateTargetHud()
  getAllPlayers().disableGamemodeHud()
  getAllPlayers().disableKillFeed()
  getAllPlayers().disablePlayerCollision()
  getAllPlayers().disableEnvironmentCollision(false)
  getAllPlayers().disableNameplatesFor(getAllPlayers())
  getAllPlayers().disableTextChat()
  getAllPlayers().disableVoiceChat(true, true, true)
```

If this works for you, please let me know and I'll close this issue.

**Comment by Ciach0** [comment]
Oh, so that's where they are
I thought they would be global because they don't accept any player in the workshop
Closing this now, thank you
