### ISSUE TITLE
Decompiler does not support comments

### ISSUE THREAD

**Issue by millionart** [Zezombye/overpy#4]
Like `//` or `/* */` ect.

**Comment by Zezombye** [comment]
Comments are like in Python: \# for a line comment and """comment""" for a multi-line comment. If you are talking about the workshop language, the decompiler does not yet support comments (but I have to fix that).

**Comment by millionart** [comment]
yeah, it is what I talk about, please fix it.

**Comment by Zezombye** [comment]
As a workaround, you can import the code within Overwatch, then export back all of it, this will remove all comments.

**Comment by Zezombye** [comment]
I have taken the position that the decompiler only supports output straight from Overwatch; this does not include the comments supported by the workshop format. As such, I am closing this issue.
