### ISSUE TITLE
How to start using Overpy

### ISSUE THREAD

**Issue by kayvanbree** [Zezombye/overpy#48]
Hello, yesterday I've been trying to get started with Overpy. I created scripts for a Reaper rework a couple of months ago and I'd like to import those to continue work without having to work in-game like a caveman. One problem: I have no clue how to import anything from the game, and I also have no clue how to get the compiled code into OW. 

Could you maybe add a chapter to the README explaining where to find these files/folders?

[edit] Also, Google is not very helpful. I've seen where to find all OW related files, except anything that has to do with the workshop.

**Comment by Zezombye** [comment]
- In the workshop editor, click on the "select all" button: 
![](https://i.imgur.com/KiQHcCA.png)

- Then, click on the "Copy" button:
![](https://i.imgur.com/AExWthc.png)

- Last, paste it into the OverPy decompiler (ctrl+shift+P then type "decompile" into the command search bar).
![](https://i.imgur.com/Ur50SYc.png)

To get the compiled code into OW, once you have compiled it, you must do "Select all", "Delete" (to remove the old rules) then "Paste" to paste the compiled code.

**Comment by kayvanbree** [comment]
Oh damn. I did not expect the copy function to actually copy code to the clipboard! I'm gonna try this as soon as I have the time for it. Thanks!
