### ISSUE TITLE
Decompiler does not support "disabled" keyword

### ISSUE THREAD

**Issue by millionart** [Zezombye/overpy#5]
- [x] Handle "disabled" for actions
- [x] Check behavior of skip if with disabled actions
- [x] Handle "disabled" for rules
- [x] Handle "disabled" for conditions

**Comment by Zezombye** [comment]
"Disabled" for actions and rules should be properly handled in 2.0

**Comment by Zezombye** [comment]
"Disabled" for conditions should be properly handled in 3.0, meaning the disabled keyword is fully supported.
