### ISSUE TITLE
PlayEffect() function not compiling when using DynamicEffect.

### ISSUE THREAD

**Issue by michael-lr** [Zezombye/overpy#51]
## Expected Behavior

`playEffect(eventPlayer, DynamicEffect.GOOD_PICKUP_EFFECT, Color.GREEN, eventPlayer.getPosition(), 1)` should be compiled resulting in `playEffect(eventPlayer, GoodPickupEffect, Green, eventPlayer, 1);`

## Current Behavior

Error message recieved upon compile attempt: `Error: Unhandled member 'GOOD_PICKUP_EFFECT'`

## Additional Information

The playEffect() function compiles when replacing DynamicEffect with Effect but produces and error message in Overwatch `Error: Expected an option after 'eventPlayer', on line 2` when pasting the code. 

## Steps to Reproduce

1. Use the playEffect() function and use any DynamicEffect
2. Attempt to compile

**Comment by Zezombye** [comment]
Thanks for reporting! I opted to clean up that mess and dynamically generate the enums based on the doc :p 

```	
//Check enums
} else if (Object.values(constantValues).map(x => x.opy).indexOf(object[0].text) >= 0) {
	return tows(object[0].text+"."+name, constantKw)```
