### ISSUE TITLE
Add wireframe models

### ISSUE THREAD

**Issue by Zezombye** [Zezombye/overpy#56]
Using the macro `createWireframeModel("path/to/file.obj", visibility, position, horizontalAngle[, verticalAngle[, tiltAngle]])` : 

- [ ] Parse .obj files to get edges
- [ ] Find the formula to rotate a model, given yaw, pitch and roll
- [ ] Implement the macro itself, with the necessary optimizations

**Comment by TrueCP6** [comment]
[This](https://stackoverflow.com/a/34060479/9819256) is the formula used for OSTW which is the only one I could find which works.

**Comment by Zezombye** [comment]
Weird, I used the same one for my tank, but the vertical rotation is off (eg if I look straight down, the cannon will be offset in front, and if I look straight up, the cannon will be offset in back).

**Comment by Zezombye** [comment]
This was supposed to one-up OSTW but i'm way too lazy to do that lul
