### ISSUE TITLE
[Feature request] CLI

### ISSUE THREAD

**Issue by kayvanbree** [Zezombye/overpy#68]
I have not really used Overpy as I have been busy getting a new job, but I just thought of this, and since my new job will not start yet, I will have time to finally really try Overpy in the coming weeks. 

It's awesome that there is a VS Code extension, however in my daily work I use Jetbrains' products. If there would be a CLI that could decompile that would be awesome. That way you could just add some run configuration that would decompile everything from the clipboard, using maybe a json file that defines the global/player variables. I don't know if reading the clipboard is possible, another option would be to paste it into a file and to decompile that. 

What do you guys think of this?

**Comment by Zezombye** [comment]
The file https://github.com/Zezombye/overpy/blob/master/VS%20Code%20Extension/overpy.js has the necessary exports to make calls to overpy from another program. I guess you could create your own js file that imports overpy (`var overpy = require("./overpy.js");`) then reads input from some file and calls `overpy.decompileAllRules(content)`, that you could call with `node`.

However, I would advise that you use the vs code extension, as else you would have to look for the function signatures every time :p

**Comment by Bluscream** [comment]
How would i go about making a build pipeline integrated with Github for a overpy project. I think about Appveyor or Travis

**Comment by Zezombye** [comment]
Closing this as there does not seem to be much need for this (with the improvements to the workshop itself, going without proper autocompletion, intellisense and syntax coloration would not be much better than coding in the GUI).
