### ISSUE TITLE
Valid rule is disallowed by compiler

### ISSUE THREAD

**Issue by dreness** [Zezombye/overpy#74]
It's legal to use 'eventPlayer' in a rule triggered by the event "player earned elimination", for example:

![image](https://user-images.githubusercontent.com/5242016/66700703-608c9e80-eca8-11e9-8397-f94b69bf363d.png)

... however, trying to write the equivalent in overpy fails because:

![image](https://user-images.githubusercontent.com/5242016/66700723-b5301980-eca8-11e9-9325-bff304dcaace.png)

The relevant logic is here:
https://github.com/Zezombye/overpy/blob/ca1119c4b289e73e5f4f34a3a55c93c406268e63/src/compiler.js#L1125-L1128

Here's a short video demo showing that this rule does actually work: https://youtu.be/_Aa714HJfTU. The 'fast restart' rule is shown in the in-game editor - this rule is triggered by the "player earned elimination" event. Then I swipe a few tracers and use the debugger to reveal that the rule executed.

Overpy rocks :)

**Comment by Zezombye** [comment]
Right, this is actually intended behavior (as you should use attacker/victim instead of eventPlayer) but I'll remove the error until I have a warning system.

Thanks for reporting :)

**Comment by Zezombye** [comment]
Behavior changed in 2.0.4.

(I didn't change the behavior for eventDamage/eventHealing/eventWasCriticalHit because, although they can be used with any event, their value will be 0 if used with an invalid event, and therefore it should definitely throw an error.)
