### ISSUE TITLE
[Feature Request] Compiler error if user accidentally puts colon after `while` in `do-while`

### ISSUE THREAD

**Issue by Tawling** [Zezombye/overpy#8]
**Issue:**
It's very easy to forget that do-while isn't a standard python construct and accidentally end the line with a colon out of habit.

Example:
```py
@Rule "Invalid while syntax"
@Event global
if B > 0:
    do:
        if A < B:
            A += 1
    while A < B:
```

This code produces this very unhelpful error:
```
Error: line 7, col 18: No match found for keyword 'B()'
    at error (utils.js:557)
    at translate (utils.js:292)
    at tows (utils.js:306)
    at parse (overpyCompiler.js:786)
    at parse (overpyCompiler.js:490)
    at compileRule (overpyCompiler.js:375)
    at compile (overpyCompiler.js:37)
```

It seems reasonable to check for this invalid syntax and return that there is an unexpected colon at the end of the line rather than this confusing error.

**Potential solution:**
Seeing as the `while` syntax requires a space and spaces are invalid in label names, an `unexpected ":" at end of line` error would catch both this error and an error with spaces in label names, along with any other invalid use of `:`

**Comment by Zezombye** [comment]
Fixed in 1.2, thanks for reporting :)

Amusingly, any other invalid use of ":" causes the line to just be dropped (as it is parsed as a label), and not throw an error.
