### ISSUE TITLE
Properly escape strings

### ISSUE THREAD

**Issue by Zezombye** [Zezombye/overpy#83]
- [x] Treat \n as a newline character.
- [x] Treat \xHH as a raw byte.
- [x] Treat \uXXXX as a unicode escape.
- [x] Treat \" and \' as " and '.
- [x] Throw an error on invalid escape.

**Comment by Zezombye** [comment]
Put on hold, as it is currently impossible to import multiline strings from copy-paste.

**Comment by nathan130200** [comment]
An idea is put some symbol at string start like in C# multiline strings starts with: `@"` and ends with `"`

**Comment by Zezombye** [comment]
An even easier way is simply to make all strings multiline: after all, there is no reason not to (like Powershell/Puppet does).

**Comment by Zezombye** [comment]
Done in 6.0
