### ISSUE TITLE
Nested `if` cannot end a rule

### ISSUE THREAD

**Issue by Tawling** [Zezombye/overpy#9]
A nested `if` statement ending a rule doesn't seem to compile correctly. 

```py
@Rule "Nested if at end of rule"
@Event global
if B > 0:
    C = true
    if A < B:
        A += 1
```
produces console error:
```
Error: line 5, col 8: weird if
    at error (utils.js:557)
    at compileRule (overpyCompiler.js:323)
    at compile (overpyCompiler.js:37)
```

But this works:
```py
@Rule "Nested if before end of rule"
@Event global
if B > 0:
    if A < B:
        A += 1
    C = true
```

At [`overpyCompiler.js:291`](https://github.com/Zezombye/overpy/blob/887dc0a239053604c7562385c4090343f356e599/overpyCompiler.js#L291) you seem to check whether the `if` statement body reaches the end of the rule and attempt to invert the condition, but it looks like you either accidentally set `isSkipIf = false` or you forgot to set `hasAbort = true`.

I would argue that keeping it as a skip-if instruction would keep the code more consistent if one were to compile and then decompile the same program, but converting it to an abort-if instruction may be more optimal depending on how the workshop interpreter is written. I'm not sure how much you care about decompilation consistency.

**Comment by Zezombye** [comment]
Fixed in 1.2, thanks for reporting!
