### ISSUE TITLE
Remove "unused vars" in compilation.

### ISSUE THREAD

**Issue by nathan130200** [Zezombye/overpy#92]
Since workshop only needs variables that is used in script, the "unused vars" in compilation output is horrible.

An example script to show how this works:

```cs
variables
{
	global:
		32: foobar
}

rule("Rule 1")
{
	event
	{
		Ongoing - Global;
	}

	actions
	{
		Set Global Variable(foobar, 0);
	}
}
```

In game (only need first A-Z variables by default):

![image](https://user-images.githubusercontent.com/14365254/69893880-7dcc0980-12f6-11ea-9d14-77abb5011483.png)

The script is imported normally without erros.

**Comment by Zezombye** [comment]
The use of the "unused vars" is for a rare case when changes would cause errors:
- Compile a program with var "foo" at position 20
- Remove the var "foo", compile again
- Add the var "foo" back but at position 21 (without having another variable at position 20): the workshop will then complain that two variables have the same name.

Though this was more of a concern when the variable indexes were calculated automatically, and this case would occur more often.

**Comment by nathan130200** [comment]
Hmm, beucase these unused vars list caused server connection lost to the game in some times, because when paste script, game thread freezes (i already reported to blizzard, but, well... they not fixed yet 😞 ).

**Comment by Zezombye** [comment]
Does it still occur on PTR? They fixed various lags related to the UI.

**Comment by nathan130200** [comment]
In PTR i didn't tested yet, i will test today.

**Comment by Zezombye** [comment]
Added the #!disableUnusedVars directive if you want to disable the generation of the unused variables.
