### ISSUE TITLE
@override rule decorators

### ISSUE THREAD

**Issue by Bluscream** [Zezombye/overpy#94]
Normally creating a rule with the same name twice will just result in 2 rules, but in special cases i want a rule to overwrite another on compile time. For example:

```py
@rule "Main"
if (bla):
  do this;

@override
@rule "Main"
if (bla):
   do that instead of this;
```

the last override should always take precedence because of imports

**Comment by Zezombye** [comment]
Seems like it could be done instead with #ifdef (#47 ), or even having a rule trigger when a variable is set to false, and the other when it is set to true (the compiler will remove the rule if one of its conditions is false).

**Comment by Bluscream** [comment]
hmm, i can't follow you right there. can you provide a code snippet of how your proposed solution would look like?

**Comment by Zezombye** [comment]
Can you provide an example of when you would use this @override annotation first?

**Comment by Bluscream** [comment]
[This](https://discordapp.com/channels/570672959799164958/570688794685079572/650520656634445824) is my example.

**Comment by Zezombye** [comment]
Neither the rule titles or the conditions are the same, so I don't know why the "change modes" rule would be overwritten :o 

Anyway the way to do it is to define a constant and toggling it, like this:

```
#!define OVERRIDE_RULE true

@rule "Main"
if not OVERRIDE_RULE and bla:
  do this;

@override
@rule "Main"
if OVERRIDE_RULE and bla:
   do that instead of this;
```

The optimizer will detect that one of the rules has a condition that is always false, and therefore remove the rule.

**Comment by Bluscream** [comment]
> Anyway the way to do it is to define a constant and toggling it, like this:

That would still require modification of the core. I need to keep it intact as is.

> Neither the rule titles or the conditions are the same, so I don't know why the "change modes" rule would be overwritten :o

I would only want to match on title and yes they are in my files because it wouldn't work anyway yet. What i "would use" in case this is implemented is something like my short example the OP, just split accross imports.

**Comment by Zezombye** [comment]
Closing as I feel this is too niche of a use case.

**Comment by Bluscream** [comment]
More like because you're too lazy :P anyway i don't play OW anymore so do as you please
